import { getRoleColor } from '../utils/roleUtils';

const Statistics = ({ stats }) => {
  if (!stats) {
    return (
      <div style={{ textAlign: 'center', padding: '40px' }}>
        <div style={{
          display: 'inline-block',
          width: '40px',
          height: '40px',
          border: '4px solid #f3f3f3',
          borderTop: '4px solid #adb5bd',
          borderRadius: '50%',
          animation: 'spin 1s linear infinite'
        }}></div>
        <p style={{ marginTop: '16px', color: '#64748b' }}>Loading statistics...</p>
      </div>
    );
  }

  return (
    <div>
      <h2 style={{
        margin: '0 0 32px 0',
        fontSize: '24px',
        fontWeight: '700',
        color: '#1e293b'
      }}>
        Statistics
      </h2>

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '24px',
        marginBottom: '32px'
      }}>
        <StatCard
          title="Total Users"
          value={stats.totalUsers}
          color="#adb5bd"
          bgColor="#f8f9fa"
        />

        <StatCard
          title="New Users (7 days)"
          value={stats.recentUsers}
          color="#198754"
          bgColor="#f8f9fa"
        />

        <StatCard
          title="Growth Rate"
          value={`${Math.round((stats.recentUsers / stats.totalUsers) * 100)}%`}
          color="#fd7e14"
          bgColor="#f8f9fa"
        />
      </div>

      <RoleDistributionChart stats={stats} />
    </div>
  );
};

const StatCard = ({ title, value, color, bgColor }) => {
  return (
    <div style={{
      backgroundColor: bgColor,
      padding: '24px',
      borderRadius: '8px',
      border: '1px solid #e9ecef',
      textAlign: 'center'
    }}>
      <h3 style={{
        margin: '0 0 8px 0',
        fontSize: '32px',
        fontWeight: '700',
        color: color
      }}>
        {value}
      </h3>
      <p style={{
        margin: 0,
        fontSize: '14px',
        fontWeight: '600',
        color: '#6c757d'
      }}>
        {title}
      </p>
    </div>
  );
};

const RoleDistributionChart = ({ stats }) => (
  <div style={{
    backgroundColor: '#f8f9fa',
    padding: '32px',
    borderRadius: '8px',
    border: '1px solid #e9ecef'
  }}>
    <h3 style={{
      margin: '0 0 24px 0',
      fontSize: '20px',
      fontWeight: '600',
      color: '#1e293b'
    }}>
      Role Distribution
    </h3>

    <div style={{ display: 'grid', gap: '16px' }}>
      {stats.roleDistribution.map(roleData => (
        <div key={roleData._id} style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '20px',
          backgroundColor: 'white',
          borderRadius: '6px',
          border: '1px solid #e9ecef'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{
              width: '48px',
              height: '48px',
              backgroundColor: getRoleColor(roleData._id),
              borderRadius: '6px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '16px',
              fontWeight: '600',
              color: 'white'
            }}>
              {roleData._id.charAt(0).toUpperCase()}
            </div>
            <div>
              <h4 style={{
                margin: '0 0 4px 0',
                fontSize: '16px',
                fontWeight: '600',
                color: '#1e293b',
                textTransform: 'capitalize'
              }}>
                {roleData._id}s
              </h4>
              <p style={{
                margin: 0,
                fontSize: '14px',
                color: '#64748b'
              }}>
                {Math.round((roleData.count / stats.totalUsers) * 100)}% of total users
              </p>
            </div>
          </div>

          <div style={{
            backgroundColor: getRoleColor(roleData._id),
            color: 'white',
            padding: '12px 20px',
            borderRadius: '4px',
            fontSize: '18px',
            fontWeight: '700'
          }}>
            {roleData.count}
          </div>
        </div>
      ))}
    </div>

    <div style={{
      marginTop: '24px',
      padding: '16px',
      backgroundColor: '#e9ecef',
      borderRadius: '6px',
      fontSize: '14px',
      color: '#495057'
    }}>
      <strong>Report generated by:</strong> {stats.requestedBy.username} ({stats.requestedBy.role})
    </div>
  </div>
);

export default Statistics;